version: 2.1

workflows:
  version: 2
  project_cicd:
    jobs:
      - build:
          context:
            - docker-hub

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - run:
          name: Building image
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM .
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
      - run:
          name: Pushing new image version
          command: |
            TERRARIA_VERSION=`cat Dockerfile | grep "ARG VERSION=" | awk -F "=" '{ print $2 }'`
            echo "Terraria version is $TERRARIA_VERSION"
            docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM $DOCKER_HUB_USERNAME/terraria:$TERRARIA_VERSION
            docker push $DOCKER_HUB_USERNAME/terraria:$TERRARIA_VERSION
      - run:
          name: Pushing latest version
          command: |
            docker tag $CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM $DOCKER_HUB_USERNAME/terraria:latest
            docker push $DOCKER_HUB_USERNAME/terraria:latest